/**
 * ATIF v1.7 — Agent Trajectory Interchange Format — TypeScript types.
 *
 * These mirror `harbor.models.trajectories` (Harbor / Laude Institute /
 * Terminal-Bench), so a tracetap-emitted document is directly consumable by
 * Harbor's validator, visualizers and SFT/RL pipelines. Field names and
 * nullability follow the pydantic models 1:1; the JSON we emit drops `undefined`
 * keys (via `JSON.stringify`), which Harbor treats as the schema default.
 *
 * The schema_version is pinned to ATIF-v1.7 — the current interchange version.
 *
 * Honest limits: `logprobs`, `prompt_token_ids` and `completion_token_ids`
 * are intentionally omitted. The Anthropic and OpenAI response streams tracetap
 * captures do not carry them, so a tracetap-sourced ATIF is first-class for
 * debugging / visualization / SFT and PARTIAL for token-level RL. We never
 * fabricate these RL-only fields.
 */

export const ATIF_SCHEMA_VERSION = "ATIF-v1.7" as const;
export type AtifSchemaVersion = typeof ATIF_SCHEMA_VERSION;

export type AtifSource = "system" | "user" | "agent";

export interface AtifImageSource {
  media_type: "image/jpeg" | "image/png" | "image/gif" | "image/webp";
  path: string;
}

export interface AtifContentPart {
  type: "text" | "image";
  text?: string;
  source?: AtifImageSource;
}

export type AtifContent = string | AtifContentPart[];

export interface AtifToolCall {
  /** Unique identifier for this specific tool call. */
  tool_call_id: string;
  /** The name of the function or tool being invoked. */
  function_name: string;
  /** Arguments passed to the function (always an object, may be empty). */
  arguments: Record<string, unknown>;
  extra?: Record<string, unknown>;
}

export interface AtifObservationResult {
  /** The `tool_call_id` (in the SAME step) this result answers, if any. */
  source_call_id?: string;
  /** Tool output. String for text-only content. */
  content?: AtifContent;
  subagent_trajectory_ref?: AtifSubagentTrajectoryRef[];
  extra?: Record<string, unknown>;
}

export interface AtifObservation {
  results: AtifObservationResult[];
}

export interface AtifMetrics {
  /** Total input tokens including cached and non-cached. */
  prompt_tokens?: number;
  /** Total tokens generated by the LLM response. */
  completion_tokens?: number;
  /** Subset of prompt_tokens that were cache hits. */
  cached_tokens?: number;
  cost_usd?: number;
  // logprobs / *_token_ids are intentionally never emitted — see file header.
  prompt_token_ids?: number[];
  completion_token_ids?: number[];
  logprobs?: number[];
  extra?: Record<string, unknown>;
}

export interface AtifStep {
  /** Ordinal index of the turn (sequential from 1). */
  step_id: number;
  /** ISO 8601 timestamp indicating when this step occurred. */
  timestamp?: string;
  source: AtifSource;
  /** Per-step model id. Agent steps only. */
  model_name?: string;
  reasoning_effort?: string | number;
  /** The dialogue message. String for text-only content. */
  message: AtifContent;
  /** The agent's explicit internal reasoning. Agent steps only. */
  reasoning_content?: string;
  /** Structured actions. Agent steps only. */
  tool_calls?: AtifToolCall[];
  observation?: AtifObservation;
  /** LLM operational data for this step. Agent steps only. */
  metrics?: AtifMetrics;
  is_copied_context?: boolean;
  llm_call_count?: number;
  extra?: Record<string, unknown>;
}

export interface AtifFinalMetrics {
  total_prompt_tokens?: number;
  total_completion_tokens?: number;
  total_cached_tokens?: number;
  total_cost_usd?: number;
  total_steps?: number;
  extra?: Record<string, unknown>;
}

export interface AtifAgent {
  /** The name of the agent system, e.g. `"claude"` / `"codex"`. */
  name: string;
  /** Version identifier of the agent system (required by ATIF). */
  version: string;
  /** Default LLM model used for this trajectory. */
  model_name?: string;
  /**
   * Tool/function definitions available to the agent, captured VERBATIM from
   * the harness's request body `tools[]`. ATIF types this as `list[dict]`.
   */
  tool_definitions?: Array<Record<string, unknown>>;
  extra?: Record<string, unknown>;
}

export interface AtifSubagentTrajectoryRef {
  /** Resolution key for embedded subagents: matches a subagent's trajectory_id. */
  trajectory_id?: string;
  /** Informational only — run identity of the delegated subagent. */
  session_id?: string;
  /** Resolution key for external-file subagent references. */
  trajectory_path?: string;
  extra?: Record<string, unknown>;
}

export interface AtifTrajectory {
  schema_version: AtifSchemaVersion;
  /** Identifier for the agent run this trajectory belongs to. */
  session_id?: string;
  /** Canonical per-trajectory-document identifier. */
  trajectory_id?: string;
  agent: AtifAgent;
  /** Complete interaction history (at least one step). */
  steps: AtifStep[];
  notes?: string;
  final_metrics?: AtifFinalMetrics;
  continued_trajectory_ref?: string;
  extra?: Record<string, unknown>;
  /** Embedded subagent trajectories (ATIF v1.7). Each is independently valid. */
  subagent_trajectories?: AtifTrajectory[];
}
